#使用mysql5.6基础镜像
FROM mysql:5.6
MAINTAINER  GTID主库 526353781@qq.com
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
COPY ./shell/gtidUser.sql /tmp/gtidUser.sql
COPY ./shell/setup.sh /tmp/setup.sh
COPY ./conf/mysql.cnf /etc/mysql/conf.d/
CMD ["sh", "/tmp/setup.sh"]
